// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `bank.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Bank;

public class NotSupportedCurrencyException extends com.zeroc.Ice.UserException
{
    public NotSupportedCurrencyException()
    {
        this.message = "Not supported currency was used";
    }

    public NotSupportedCurrencyException(Throwable cause)
    {
        super(cause);
        this.message = "Not supported currency was used";
    }

    public NotSupportedCurrencyException(String message)
    {
        this.message = message;
    }

    public NotSupportedCurrencyException(String message, Throwable cause)
    {
        super(cause);
        this.message = message;
    }

    public String ice_id()
    {
        return "::Bank::NotSupportedCurrencyException";
    }

    public String message;

    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::Bank::NotSupportedCurrencyException", -1, true);
        ostr_.writeString(message);
        ostr_.endSlice();
    }

    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        message = istr_.readString();
        istr_.endSlice();
    }

    public static final long serialVersionUID = 1720716138L;
}
