// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `bank.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Bank;

public class PersonData implements java.lang.Cloneable,
                                   java.io.Serializable
{
    public String name;

    public String lastName;

    public String pesel;

    public PersonData()
    {
        this.name = "";
        this.lastName = "";
        this.pesel = "";
    }

    public PersonData(String name, String lastName, String pesel)
    {
        this.name = name;
        this.lastName = lastName;
        this.pesel = pesel;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        PersonData r = null;
        if(rhs instanceof PersonData)
        {
            r = (PersonData)rhs;
        }

        if(r != null)
        {
            if(this.name != r.name)
            {
                if(this.name == null || r.name == null || !this.name.equals(r.name))
                {
                    return false;
                }
            }
            if(this.lastName != r.lastName)
            {
                if(this.lastName == null || r.lastName == null || !this.lastName.equals(r.lastName))
                {
                    return false;
                }
            }
            if(this.pesel != r.pesel)
            {
                if(this.pesel == null || r.pesel == null || !this.pesel.equals(r.pesel))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Bank::PersonData");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, name);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lastName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, pesel);
        return h_;
    }

    public PersonData clone()
    {
        PersonData c = null;
        try
        {
            c = (PersonData)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.name);
        ostr.writeString(this.lastName);
        ostr.writeString(this.pesel);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.name = istr.readString();
        this.lastName = istr.readString();
        this.pesel = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, PersonData v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public PersonData ice_read(com.zeroc.Ice.InputStream istr)
    {
        PersonData v = new PersonData();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<PersonData> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, PersonData v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<PersonData> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(PersonData.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final PersonData _nullMarshalValue = new PersonData();

    public static final long serialVersionUID = -969234006L;
}
